# -------------------------------------------------------------------------------------------
#
#  Welcome to OmegaNames' main configuration file.
#
#  Here you'll find of the settings and options that you can
#  customize to your server needs. Most features are customizable
#  to an extent.
#
# For help you can visit the wiki at: https://github.com/OmegaWeaponDev/OmegaNames/wiki
# If you have any issues, report them here: https://github.com/OmegaWeaponDev/OmegaNames/issues
#
#  Colours:
#   - darkred
#   - red
#   - gold
#   - yellow
#   - green
#   - lime
#   - aqua
#   - darkaqua
#   - darkblue
#   - blue
#   - pink
#   - purple
#   - white
#   - lightgray
#   - gray
#   - black
#
# -------------------------------------------------------------------------------------------

# If true, each of the colours will require a specific permission
# Use the permission `omeganames.namecolours.colour.<colour>` or `omeganames.namecolours.colour.*`
# If false, use the permission `omeganames.namecolours.colours`
Per_Name_Colour_Permissions: false

# If true, when a player gets a name colour it will show the name colour on tablist
Tablist_Name_Colour: true

# If true, players will retain their name colour when they login/logout
Name_Colour_Login: true

# The default namecolour players will have if they have not chosen a current name colour
Default_Name_Colour: "&e"

# Set all the different name colours and the item that you want in the GUI
# This will accept both the normal colour codes (&4) and hex colour codes (#123456)
Items:
  Dark Red:
    Colour: "#670E00"
    Item: NETHER_WART
  Red:
    Colour: "#FF0101"
    Item: RED_WOOL
  Gold:
    Colour: "#FFDC01"
    Item: GOLD_BLOCK
  Yellow:
    Colour: "#FFFB01"
    Item: YELLOW_WOOL
  Green:
    Colour: "#1FAA00"
    Item: GREEN_WOOL
  Lime:
    Colour: "#36FF09"
    Item: LIME_DYE
  Aqua:
    Colour: "#09FFEC"
    Item: LIGHT_BLUE_WOOL
  Dark Aqua:
    Colour: "#00B4A6"
    Item: CYAN_WOOL
  Dark Blue:
    Colour: "#000E86"
    Item: BLUE_WOOL
  Blue:
    Colour: "#004DFF"
    Item: BLUE_ORCHID
  Pink:
    Colour: "#FF00FF"
    Item: PINK_TULIP
  Purple:
    Colour: "#8000FF"
    Item: MAGENTA_SHULKER_BOX
  White:
    Colour: "#FFFFFF"
    Item: QUARTZ_BLOCK
  Light Gray:
    Colour: "#CBCBCB"
    Item: LIGHT_GRAY_WOOL
  Gray:
    Colour: "#818181"
    Item: STONE
  Black:
    Colour: "#000000"
    Item: BLACK_WOOL

# Group Specific name colours.
# Use the permission `omeganames.namecolour.groups.<group name>`
Group_Name_Colour:
  # Whether or not you want per-group name colours
  Enabled: true
  # The groups and their respective name colour
  Groups:
    owner: '&4'
    admin: '&b'

# If true, players with the permission `omeganames.update` will receive update messages
Update_Messages: true

# DO NOT EDIT THIS
Config_Version: 1.0