# -------------------------------------------------------------------------------------------
#
#  Welcome to Stylizer's main configuration file.
#
#  Here you'll find of the settings and options that you can
#  customize to your server needs. Most features are customizable
#  to an extent.
#
#  For help you can visit the wiki at: https://github.com/OmegaWeaponDev/OmegaNames/wiki
#  If you have any issues, report them here: https://github.com/OmegaWeaponDev/OmegaNames/issues
#
#  Stylizer Placeholders:
#    %displayname% - Gets the players namecolour and name.
#    %message% - Gets the players chat message.
#
#
# -------------------------------------------------------------------------------------------

# If true, each of the colours will require a specific permission
# Use the permission `stylizer.namecolour.colour.<colour>` or `stylizer.namecolour.colour.all`
# If false, use the permission `stylizer.namecolour.colours`
Per_Name_Colour_Permissions: false

# If true, when a player gets a name colour it will show the name colour on tablist
Tablist_Name_Colour: true

# Apply the players prefix and suffix to their tablist name along with your name colour
Tablist_Prefix_Suffix: true

# If true, players will retain their name colour when they login/logout
Name_Colour_Login: true

# The default namecolour players will have if they have not chosen a current name colour
Default_Name_Colour: "&e"

# Set all the different name colours and the item that you want in the GUI
# This will accept both the normal colour codes (&4) and hex colour codes (#123456)
Items:
  Dark Red:
    Colour: "#670E00"
    Item: NETHER_WART
  Red:
    Colour: "#FF0101"
    Item: RED_WOOL
  Gold:
    Colour: "#FFDC01"
    Item: GOLD_BLOCK
  Yellow:
    Colour: "#FFFB01"
    Item: YELLOW_WOOL
  Green:
    Colour: "#1FAA00"
    Item: GREEN_WOOL
  Lime:
    Colour: "#36FF09"
    Item: LIME_DYE
  Aqua:
    Colour: "#09FFEC"
    Item: LIGHT_BLUE_WOOL
  Dark Aqua:
    Colour: "#00B4A6"
    Item: CYAN_WOOL
  Dark Blue:
    Colour: "#000E86"
    Item: BLUE_WOOL
  Blue:
    Colour: "#004DFF"
    Item: BLUE_ORCHID
  Pink:
    Colour: "#FF00FF"
    Item: PINK_TULIP
  Purple:
    Colour: "#8000FF"
    Item: MAGENTA_SHULKER_BOX
  White:
    Colour: "#FFFFFF"
    Item: QUARTZ_BLOCK
  Light Gray:
    Colour: "#CBCBCB"
    Item: LIGHT_GRAY_WOOL
  Gray:
    Colour: "#818181"
    Item: STONE
  Black:
    Colour: "#000000"
    Item: BLACK_WOOL

# Group Specific name colours.
# Use the permission `stylizer.namecolour.groups.<group name>`
Group_Name_Colour:
  # Whether or not you want per-group name colours
  Enabled: true
  # The groups and their respective name colour
  Groups:
    owner: '&4'
    admin: '&b'

# Here you are able to stylize how your chat messages look!
# All PlaceholderAPI placeholders can be used!
Chat_Settings:
  # Whether or not you want Stylizer to style the chat.
  Enabled: true
  # Whether you want Stylizer to log all the chat messages.
  Log_Chat_Messages: false
  # This is where you can determine the different formats that players will use in chat messages.
  Chat_Formats:
    # This is the main chat format that all players will have if they don't have one of the group formats below.
    Default_Format: "%displayname% #14abc9>> #6b6b6b%message%"
    # Settings for the group chat formats.
    Group_Formats:
      # Whether you want Stylizer to handle group chat formats.
      Enabled: true
      # The different group formats that you want to implement.
      # Playes will need the permissions `stylizer.chat.group.<group name>` to use one of the formats below.
      Groups:
        member: "%prefix% %displayname% %suffix%#14abc9>> #6b6b6b%message%"
        admin: "#6b6b6b&l[#570000STAFF#6b6b6b&l] %prefix% %displayname% %suffix%#14abc9>> #ff4a4a%message%"
        owner: "#6b6b6b&l[#570000STAFF#6b6b6b&l] %prefix% %displayname% %suffix%#ff4a4a>> #14abc9%message%"

# Stylize how you would like the tablist to look like
Tablist:
  # Whether or not you want Stylizer to style the tablist.
  Enabled: true
  # The tablist header message
  # Use %player% to get the players name (Prefixes and Suffixes included)
  Tablist_Header: "#14abc9Welcome to the server %player%"
  Tablist_Footer:
    - "#14abc9Don't forget to check out our website!"
    - "#14abc9Please remember to vote for us!"

# Set some special announcement messages that will be broadcast to your whole server.
Announcement_Messages:
  # Whether or not you want Stylizer to use annoucement messages.
  Enabled: true
  # The messages to be broadcast
  # All messages fully support PlaceholderAPI placeholders.
  Messages:
    - "#fc0356Remember to vote for the server www.ourwebsite.com/vote"
    - "#90fc03Get a free member rank on our website! www.ourwebsite.com/member"
  # The time inbetween each announcement message.
  # The time is in seconds.
  Interval: 600

# Display a pretty message for your server in the multiplayer server list
Server_Listing:
  # Whether or not you want Stylizer to display a message.
  Enabled: true
  # The message that you want displayed.
  Format:
    - "#14abc9[+] #ff4a4aEveryone is welcome! #14abc9[+]"
    - "#14abc9=[*]= #ff4a4aAn amazing social minecraft server #14abc9=[*]="

# If true, players with the permission `stylizer.update` will receive update messages
Update_Messages: true

# DO NOT EDIT THIS
Config_Version: 2.2