name: ${project.name}
version: ${project.version}
api-version: 1.15
description: ${project.description}
main: ${main.class}

author: ${pl.author}

softdepend:
  - PlaceholderAPI

commands:
  omeganames:
    description: The main command for OmegaNames
    usage: /omeganames
    aliases: [on, onames, omegan]
  namecolour:
    description: The name colour command
    usage: /namecolour
    aliases: [nc, namec, namecolours, ncolours]

permissions:
  omeganames.admin:
    description: Grants the user access to all the main permissions, but not group colours
    default: false
    children:
      - omeganames.reload
      - omeganames.update
      - omeganames.namecolour.add
      - omeganames.namecolour.remove
      - omeganames.namecolour.colours
      - omeganames.namecolour.colour.all
      - omeganames.namecolour.login
      - omeganames.namecolour.open
      - omeganames.namecolour.custom
  omeganames.reload:
    description: Grants the user access to the reload command
    default: false
  omeganames.update:
    description: Allows the user to recieve the update messages in-game
    default: false
  omeganames.namecolour.open:
    description: Grants the user access to the name colour command
    default: false
  omeganames.namecolour.login:
    description: Allows the user to retain their name colour when they login/logout
    default: false
  omeganames.namecolour.colours:
    description: Allows the user to use all the colours if Per_Name_Colour_Permissions is disabled
    default: false
  omeganames.namecolour.colour.all:
    description: Allows the user to use all the colours if Per_Name_Colour_Permissions is enabled
    default: false
  omeganames.namecolour.add:
    description: Allows the user to use the name colour add command
    default: false
  omeganames.namecolour.remove:
    description: Allows the user to use the name colour remove command
    default: false
  omeganames.namecolour.custom:
    description: Allows the user to use the custom name colour command